import {
  Bot,
  ClipboardList,
  HeartPulse,
  Sparkles,
  Stethoscope,
  UserRoundCheck,
} from 'lucide-react';

export const DEMO_STEPS = [
  {
    id: 'today',
    tab: 'home',
    eyebrow: 'Momen 1',
    title: 'Hari ini dibuat sederhana',
    summary: 'Tunjukkan bagaimana app memulai dari satu langkah realistis, bukan dashboard yang penuh.',
    proof: 'User bisa check-in, melihat alasan AI, dan mencatat dengan input minimal.',
    Icon: HeartPulse,
    color: 'bg-teal-50 text-teal-700',
  },
  {
    id: 'plan',
    tab: 'plan',
    eyebrow: 'Momen 2',
    title: 'Plan punya arah',
    summary: 'Buka plan 7 hari untuk menunjukkan bahwa aksi harian terhubung ke tujuan kesehatan.',
    proof: 'Ini membuat produk terasa seperti companion, bukan tracker kosong.',
    Icon: ClipboardList,
    color: 'bg-emerald-50 text-emerald-700',
  },
  {
    id: 'ai',
    tab: 'ai',
    eyebrow: 'Momen 3',
    title: 'AI menjelaskan dan menyesuaikan',
    summary: 'Tunjukkan AI bisa membantu hari ini, membaca pola, atau menyiapkan ringkasan ahli.',
    proof: 'Bagian pentingnya adalah alasan AI: user melihat kenapa saran diberikan.',
    Icon: Bot,
    color: 'bg-slate-100 text-slate-900',
  },
  {
    id: 'care',
    tab: 'clinic',
    eyebrow: 'Momen 4',
    title: 'Bantuan ahli tetap chat-first',
    summary: 'Masuk ke Perawatan untuk menunjukkan jalur dari AI ke booking chat ahli.',
    proof: 'Ahli diposisikan sebagai validasi dan bimbingan, bukan marketplace terpisah.',
    Icon: Stethoscope,
    color: 'bg-amber-50 text-amber-700',
  },
  {
    id: 'memory',
    tab: 'profile',
    subView: 'health-memory',
    eyebrow: 'Momen 5',
    title: 'App mengingat konteks',
    summary: 'Buka Memori Kesehatan untuk menunjukkan pola, log, dan perubahan yang terkumpul.',
    proof: 'Nilainya sulit ditiru karena tumbuh dari perjalanan user, bukan hanya fitur.',
    Icon: Sparkles,
    color: 'bg-violet-50 text-violet-700',
  },
  {
    id: 'passport',
    tab: 'profile',
    eyebrow: 'Momen 6',
    title: 'Profil menjadi Paspor Kesehatan',
    summary: 'Tutup dengan ringkasan profil yang siap dibawa ke chat ahli.',
    proof: 'Demo punya closing kuat: tujuan, riwayat, trust layer, dan handoff konsultasi.',
    Icon: UserRoundCheck,
    color: 'bg-cyan-50 text-cyan-700',
  },
];
